<div class="support">
  <h3>Need Help?</h3>
  <p>If you are having difficulty using this form or this site, please send an email to: <a href="mailto:support@interaction.ixda.org">support@interaction.ixda.org</a>.</p>
  <?php if(strpos($_SERVER["REQUEST_URI"], "submit") || strpos($_SERVER["REQUEST_URI"], "thank-you")): ?>
  <p>For questions concerning submissions or the program in general, please contact: <a href="mailto:submissions@interaction.ixda.org">submissions@interaction.ixda.org</a>.</p>
  <?php endif; ?>
</div>
